name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build & attach asset
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows commits + release uploads

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Update lockfile
        run: npm install --package-lock-only

      - name: Commit package-lock.json when missing
        run: |
          if git status --porcelain | grep -q package-lock.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: generate package-lock.json [skip ci]"
            git push
          fi

      - name: Build
        run: |
          npm run clean
          npm run build

      - name: Commit built dist file (force-add ignored file)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ ! -f dist/item-list-card.js ]; then
            echo "dist/item-list-card.js not found; skipping commit."
            exit 0
          fi

          # force add ignored dist file
          git add -f dist/item-list-card.js

          # only continue if there are staged changes
          if git diff --cached --quiet; then
            echo "No changes to dist/item-list-card.js; skipping commit."
            exit 0
          fi

          git commit -m "chore: add dist/item-list-card.js [skip ci]"

          # Ensure we’re on the main branch and up-to-date
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          echo "Pushing built file commit to origin/main"
          git push origin main


      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/item-list-card.js
