name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write   # only required the first time we generate the lock-file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'   # speeds up repeated “npm install”

      # -----------------------------------------------------------------
      # One single install — never npm ci — will always succeed
      # -----------------------------------------------------------------
      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Commit fresh package-lock.json when it did not exist
        run: |
          if git status --porcelain | grep -q "package-lock.json"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: generate package-lock.json"
            git push origin HEAD
          fi

      - name: Build
        run: npm run build

      - name: List build artifacts
        run: ls -la dist || true

      - name: Upload JS asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
