name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write          # allow the job to push back the lock-file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ------------------------------------------------------------------
      # One single place that generates / validates the lock-file
      # ------------------------------------------------------------------
      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json missing – running npm install to create it"
            npm install --no-audit --no-fund

            # Commit and push the new lock-file
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: create package-lock.json for deterministic builds"
            git push origin HEAD
          else
            echo "Using cached package-lock.json – running npm ci"
            npm ci --no-audit --no-fund
          fi

      - name: Build
        run: npm run build

      - name: List build artifacts
        run: ls -la dist || true

      - name: Upload JS asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
