name: Release

on:
  release:
    types: [published]   # runs when a Release is published

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # Use npm ci when package-lock.json is present for deterministic builds.
        # Falls back to npm install otherwise.
        run: |
          if [ -f package-lock.json ]; then
            npm ci --prefer-offline --no-audit --no-fund
          else
            npm install --prefer-offline --no-audit --no-fund
          fi

      - name: Build
        run: npm run build
        # If your build outputs to a subfolder (e.g. dist/), no path changes needed;
        # the action runs in repo root.

      - name: List build artifacts
        run: ls -la dist || true

      - name: Upload JS asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
