name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build & attach asset
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows commits + release uploads

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Always non-brittle install; no npm ci
      - name: Install deps
        run: npm install --no-audit --no-fund

      # If lock-file was just created, commit + push back once
      - name: Commit package-lock.json when missing
        run: |
          if git status --porcelain | grep -q package-lock.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: generate package-lock.json [skip ci]"
            git push
          fi

      # Clean, then single-file build
      - name: Build
        run: |
          npm run clean
          npm run build
          
      # Commit built dist file back to the repo if it changed
      - name: Commit built dist file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # only commit if dist/item-list-card.js exists and changed
          if [ -f dist/item-list-card.js ] && git status --porcelain | grep -q "dist/item-list-card.js"; then
            git add dist/item-list-card.js
            git commit -m "chore(release): add dist/item-list-card.js [skip ci]"
            git push
          else
            echo "No dist/item-list-card.js changes to commit."
          fi
      
      # Attach dist/item-list-card.js to the GitHub release
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/item-list-card.js
